### ISSUE TITLE
Installation error with play install command

### ISSUE THREAD

**Issue by ahmetb** [play-components/play-fbconnect#11]
I'm trying to install the module on my device. However, it fails for some reason. I'm using play-1.2.3 and using `play install fbconnect-0.6`.

```
$ play install fbconnect-0.6
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
~
~ play! 1.2.3, http://www.playframework.org
~
~ Will install fbconnect-0.6
~ This module is compatible with: 1.2
~ Do you want to install this version (y/n)? y
~ Installing module fbconnect-0.6...
~
~ Fetching http://www.playframework.org/modules/fbconnect-0.6.zip
~ [--------------------------100%-------------------------] 33229.5 KiB/s   
~ Unzipping...
Traceback (most recent call last):
  File "/Users/alp/play-1.2.3/play", line 153, in <module>
    status = cmdloader.commands[play_command].execute(command=play_command, app=play_app, args=remaining_args, env=play_env, cmdloader=cmdloader)
  File "/Users/alp/play-1.2.3/framework/pym/play/commands/modulesrepo.py", line 58, in execute
    install(app, args, env)
  File "/Users/alp/play-1.2.3/framework/pym/play/commands/modulesrepo.py", line 391, in install
    Unzip().extract(archive, os.path.join(env["basedir"], 'modules/%s-%s' % (module, v['version'])))
  File "/Users/alp/play-1.2.3/framework/pym/play/commands/modulesrepo.py", line 152, in extract
    outfile = open(os.path.join(dir, name), 'wb')
IOError: [Errno 13] Permission denied: '/app/controllers/FBConnect.java'
```

Then I try it with `sudo`.

```
$ sudo play install fbconnect-0.6
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
~
~ play! 1.2.3, http://www.playframework.org
~
~ Will install fbconnect-0.6
~ This module is compatible with: 1.2
~ Do you want to install this version (y/n)? y
~ Installing module fbconnect-0.6...
~
~ Fetching http://www.playframework.org/modules/fbconnect-0.6.zip
~ [--------------------------100%-------------------------] 25840.4 KiB/s   
~ Unzipping...
~
~ Module fbconnect-0.6 is installed!
~ You can now use it by adding it to the dependencies.yml file:
~
~ require:
~     play -> fbconnect 0.6
```

However after navigating to the folder using

```
$ cd fbconnect-0.6
```

only the following files are installed:

```
README.md build.xml manifest
```

what can be the problem?

**Comment by rakyll** [comment]
I'm experiencing the same problem, although I had no errors prompting due to the lack of the permissions. But, the installation directory doesn't contain the whole module:

```
dev:fbconnect-0.6 burcu$ ls
README.md   build.xml   manifest
```

I'm trying to install fbconnect-0.6 and using play-1.2.4.

If anyone is experiencing the following exception, it may be due to an incomplete installation. Check your module's directory.

```
Template not found
The template tags/fbconnect/button.html or tags/fbconnect/button.tag does not exist.
```

**Comment by ahmetb** [comment]
I've solved the same problem switching to OAuth & OAuth2 module that comes with Play framework as builtin. There is a sample project under `samples-and-tests/facebook-oauth2`.

**Comment by distvan** [comment]
I have done as you and got error. I think the zip file is corrupt. I cloned its git repo and placed the files into the "fbconnect-0.6" modules directory manually.

**Comment by rakyll** [comment]
I had no problem with unzipping the file and copying the rest of the files manually to the module directory.
