### ISSUE TITLE
NullPointer exception when running functional tests in console

### ISSUE THREAD

**Issue by mkotsur** [play-components/play-fbconnect#7]
Version: fbconnect-head

play auto-test results with:

```
    Caused by: java.lang.NullPointerException
        at tags.fbconnect.FBConnectTags._button(FBConnectTags.java:26)
        at tags.fbconnect.FBConnectTags$_button.call(Unknown Source)
        at /app/views/Application/displayComix.html.(line:92)
```

Running test in browser goes smoothly though.

This happens on page which contains fbconnect button.

**Comment by mmurray** [comment]
Thanks for the report. This should be fixed in fbconnect-head, fbconnect-0.5, and the git master.
