### ISSUE TITLE
Not compatible with Play 1.2.2

### ISSUE THREAD

**Issue by 0xRoch** [play-components/play-fbconnect#9]
@673lhjoh8
Cannot start in PROD mode with errors

Compilation error (In {module:fbconnect-0.5}/app/controllers/FBConnect.java around line 39)
The file {module:fbconnect-0.5}/app/controllers/FBConnect.java could not be compiled. Error raised is : The method newRequest(String, String) in the type WSUrlFetch is not applicable for the arguments (String)

play.exceptions.CompilationException: The method newRequest(String, String) in the type WSUrlFetch is not applicable for the arguments (String)
    at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:246)
    at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:672)
    at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:516)
    at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:278)
    at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:412)
    at play.Play.preCompile(Play.java:563)
    at play.Play.init(Play.java:291)
    at play.server.Server.main(Server.java:158)
~
~ Precompilation has failed, stop deploying.
~

**Comment by loicguillois** [comment]
for me, it seems that the problem occurs using openjdk-6 package instead of the sun one

**Comment by francisdb** [comment]
I'm having this with Sun JDK

java -version
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02, mixed mode)

play version
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ | |/ _' | || |_|
~ |  **/|_|__**|__ (_)
~ |_|            |__/  
~
~ play! 1.2.3, http://www.playframework.org
~
1.2.3

**Comment by 0xRoch** [comment]
https://github.com/murz/play-fbconnect/pull/10 fix it
